### ISSUE TITLE
Fix for llvm

### ISSUE THREAD

**Issue by caand** [intel/ARM_NEON_2_x86_SSE#1]
A small fix is needed for llvm, because it defines __GNUC__, but it has different needs.
For some reason (repo setup) I cannot create a pull request, so here is the diff:

@@ -2251,7 +2251,7 @@ poly16x8x2_t vuzpq_p16(poly16x8_t a, poly16x8_t b); // VUZP.16 q0,q0
 // the following macros solve the problem of the "immediate parameters requirement" for some x86 intrinsics.
 // we need it to compile the code unless the "Intrinsic parameter must be an immediate value" error is our goal
 //
-#if ( ((defined(_MSC_VER)|| defined (__INTEL_COMPILER)) && defined DEBUG ) || defined(__GNUC__) )
+#if ( ((defined(_MSC_VER)|| defined (__INTEL_COMPILER)) && defined DEBUG ) || defined(__GNUC__) && !defined(__llvm__) )

     #define _MM_ALIGNR_EPI8 _mm_alignr_epi8

**Comment by Zvictoria** [comment]
Thanks a lot! For me the most valuable pieces of information are that issues notifications and pull requests don't work for some reason with this repo  :). Will investigate and fix it if possible.
And I will integrate your llvm change for sure
