### ISSUE TITLE
_mulx_u64 support

### ISSUE THREAD

**Issue by liorbiu** [intel/ARM_NEON_2_x86_SSE#13]
Hi,

Is your library supports _mulx_u64 instructions?

Lior

**Comment by Zvictoria** [comment]
Hi, to be honest I don't understand your question. _mulx_u64  doesn't look like ARM instruction or Intel SSE one either. So the answer is obvious - no it is not supported. Or could you please elaborate your question?

**Comment by liorbiu** [comment]
Hi Victoria,
Thank you for your reply.
I have a C++ code that uses Intel [SSE](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mulx_u64&expand=3773) instruction. I want to use my code on ARM devices as well.
Is there an implementation that convert this SSE instruction to ARM?

**Comment by Zvictoria** [comment]
Yes, there is. Say https://github.com/jratcliff63367/sse2neon
