### ISSUE TITLE
Extensive Correctness Tests for the ARM Neon Intrinsic Functions

### ISSUE THREAD

**Issue by lcy1991ycl** [intel/ARM_NEON_2_x86_SSE#14]
How do you do the extensive correctness tests for the ARM Neon intrinsic functions? Could  you share the test report, or the test code?

**Comment by Zvictoria** [comment]
The solution for the functions implemented passes extensive correctness tests for the ARM Neon intrinsic functions https://github.com/christophe-lyon/arm-neon-tests 
I will add it to the project description, thanks for the hint :)

**Comment by lcy1991ycl** [comment]
But it is not for the functions implemented with SSE instructions, it is for ARM/NEON instructions. https://github.com/christophe-lyon/arm-neon-tests

**Comment by Zvictoria** [comment]
Then I don't understand your question, sorry. If you want to test the SSE implementation of ARM NEON set - just use this header for the tests set mentioned above and compare with the original arm_neon.h based version.

**Comment by lcy1991ycl** [comment]
That's what I mean. But the tests set mentioned above is for an ARM target or an ARM simulator, doesn't support execution on the Intel platform.

**Comment by lcy1991ycl** [comment]
I am confused the extensive correctness tests that you have done and passed. Could you introduce it to me in detail? Maybe, you can share the test report with us.

**Comment by Zvictoria** [comment]
Well, that's what my project is about - to facilitate ARM project port to x86 :) therefore I've just took the ARM tests mentioned and applied my tool there. Except for that some minor corrections were necessary to make it running on x86 in my setup (say some other auxiliary headers inclusion/exclusion) but I don't plan to share it anywhere, sorry - they are for my own usage only. The test set mentioned has the perfect test report as an output - just use it :)

**Comment by lcy1991ycl** [comment]
The report that I mean is not the output, but the precision, just as the output of which function implemented is different, and how much the difference is.

**Comment by lcy1991ycl** [comment]
#pragma once
#include <string>
#include <chrono>
#include <iostream>
#include <vector>

//////////////////////////////////////////////////////////////////////////
//scope exit
namespace
{
	template <typename FuncType>
	class InnerScopeExit
	{
	public:
		InnerScopeExit(const FuncType _func) :func(_func){}
		~InnerScopeExit(){ if (!dismissed){ func(); } }
	private:
		FuncType func;
		bool dismissed = false;
	};
	template <typename F>
	InnerScopeExit<F> MakeScopeExit(F f) 
	{
		return InnerScopeExit<F>(f);
	};
}
#define DO_STRING_JOIN(arg1, arg2) arg1 ## arg2
#define STRING_JOIN(arg1, arg2) DO_STRING_JOIN(arg1, arg2)
#define SCOPEEXIT(code) auto STRING_JOIN(scope_exit_object_, __LINE__) = ::MakeScopeExit([&](){code;});

//////////////////////////////////////////////////////////////////////////
//function cost time calculate helper
class FuncCostTimeHelper
{
public:
	FuncCostTimeHelper(const std::string& _tag) :tag(_tag)
	{
		start_time = std::chrono::high_resolution_clock::now();
	}
	~FuncCostTimeHelper()
	{
		stop_time = std::chrono::high_resolution_clock::now();
		const auto cost_time = std::chrono::duration_cast<std::chrono::microseconds>(stop_time - start_time).count(); //us
		std::cout << tag << " cost time : " << cost_time << " us" << std::endl;
	}
private:
	std::string tag;
	std::chrono::high_resolution_clock::time_point start_time;
	std::chrono::high_resolution_clock::time_point stop_time;
};

**Comment by lcy1991ycl** [comment]
Is this header nessesary to include?

**Comment by Zvictoria** [comment]
When I say "it passes the test" is means output is the same :) The only difference is in some floating point approximations and I don't remember the exact difference order of magnitude but it is acceptable for generic usage for sure.
As for exact test modifications (what headers, defines etc to include) - the honest answer is - I don't remember and don't plan to look into it in foreseeable future, sorry. Here you are on your own. Just to mention - everything depends on your setup. My one has been for Visual Studio 2013.

**Comment by lcy1991ycl** [comment]
OK, thank you very much.
