### ISSUE TITLE
Can't compile in vs2015

### ISSUE THREAD

**Issue by hset911** [intel/ARM_NEON_2_x86_SSE#18]
I use vs2015,when I include it in my project.
complie it .
will occurred many errors.
such as :
The overloaded function "__m64_128" is not a type name
……
'vqaddq_s64': The function may be very slow due to the serial implementation, please try to avoid it.
……

What should I do to avoid this errors.

**Comment by Zvictoria** [comment]
Hi there. Looks like in your project properties you have some "Treat warnings as errors" option set. You need to switch it off for successful compilation. For the purpose please disable the SDL checks in С/С++ General properties and also "Treat warnings as errors" on the same tab. It should help. If not, please keep complaining :)

**Comment by hset911** [comment]
Perfect, your solution is simple and direct. You can turn this question off.
Thank you very much!!  :)
