### ISSUE TITLE
vqshlq_s64 or 32 return -1 when shift bit = 0

### ISSUE THREAD

**Issue by zquang** [intel/ARM_NEON_2_x86_SSE#19]
I found that vqshlq_s64 or 32 return -1 when shift bit = 0. But when change to vshlq_s64, it is OK.

**Comment by Zvictoria** [comment]
Please try the latest version.

**Comment by Zvictoria** [comment]
Hi there,  could you please confirm it works? I'd like to close this issue...

**Comment by zquang** [comment]
Oh. It works.
Many thank for your support.
Tony.

2018년 12월 27일 (목) 오후 10:32에 Victoria <notifications@github.com>님이 작성:
