### ISSUE TITLE
A64 neon intrinsics not support

### ISSUE THREAD

**Issue by zjd1988** [intel/ARM_NEON_2_x86_SSE#21]
I have checked the latest NEON_2_SSE.h ,and don't find A64 intrinsic vaddw_high_u32

**Comment by Zvictoria** [comment]
That's true. Full A64 NEON support is not implemented in this project. You may do it yourself however

**Comment by zjd1988** [comment]
@Zvictoria  thank you for your reply! I plan to use python to simulate neon intrinsics.

**Comment by Zvictoria** [comment]
You may do that, I just need to warn - it will be not good for performance....
