### ISSUE TITLE
error: member reference base type 'float [2]' is not a structure

### ISSUE THREAD

**Issue by slevental** [intel/ARM_NEON_2_x86_SSE#29]
Looks like there is a bug in the code rr[0] is a `float`, but I guess is that union type is expected ( `float32x2_t` ?)

```
/NEON_2_SSE.h:6902:3: error: member reference base type 'float [2]' is not a structure or union
  _M64f(rr[0], s_f);
  ^~~~~~~~~~~~~~
```

**Comment by slevental** [comment]
@Zvictoria could you please take a look.

**Comment by Zvictoria** [comment]
Mega thanks! I will close this issue if you don't complain about the new version.
