### ISSUE TITLE
Could there be a precision error between sse and neon?

### ISSUE THREAD

**Issue by forMwish** [intel/ARM_NEON_2_x86_SSE#38]
For example, floating point Numbers?
Thanks. My project has some errors between arm and intel, and I'm not sure where that happened

**Comment by Zvictoria** [comment]
Hi. Sure some error on floating point numbers treatment exists, especially on reciprocal, sqrt, floqt->int conversion etc. Moreover unfortunately original ARM and my implementation treat NAN and over-underflow differently. It might be the point. If you make the whole list of functions used in your app I may point you the suspicious ones. For the purposes just compile your app  without this header and the list of errors (functions undefined) will be the thing to share

**Comment by forMwish** [comment]
I am glad to receive your reply. Luckily I find the error (vrecpe / vrsqrte) by android web .Finally, I used C to implement the corresponding pseudo-code on the arm architecture manual but not implement the exception handler. Now, it work.
Thank you very much.
