### ISSUE TITLE
MIT licensed copy?

### ISSUE THREAD

**Issue by nemequ** [intel/ARM_NEON_2_x86_SSE#4]
I've been working on a similar project called [SIMDe](https://github.com/nemequ/simde) lately, with the goal of being able to use any SIMD instruction set (MMX/SSE*/AVX*, NEON, MSA, AltiVec/VSX, etc.) anywhere.  Until now I've mostly focused on writing portable implementations x86/x86_64 SIMD intrinsics, but I'd like to start working on [implementing NEON](https://github.com/nemequ/simde/issues/10).

Using code from this project would give us a huge boost, but SIMDe uses an MIT license.  Given that this project is also using a very permissive license, I was wondering if it would be possible to get an MIT-licensed version?  It's probably not a deal-breaker for us, but if possible I'd like to keep the licensing as simple as possible, and a single license would really help.

**Comment by Zvictoria** [comment]
Unfortunately while the whole content of this repo is mine, the license questions are under responsibility of Intel legal - you need to contact them for such requests  :)
