### ISSUE TITLE
Any plans for adding ARMv8 support?

### ISSUE THREAD

**Issue by dawadaq** [intel/ARM_NEON_2_x86_SSE#45]
Currently, NEON_2_SSE only supports ARMv7 NEON intrinsics.
Is there a plan to add support for ARMv8 intrinsics, such as vaddlvq_u8()?t

**Comment by Zvictoria** [comment]
Hi, @dawadaq It is not the first request of such kind I receive so I couldn't reply "no". But I couldn't reply "yes, there is" either. The key problem here is the tests set for ARMv8 availability. The current test set used doesn't have these instructions unfortunately.
Therefore if you find some extensive tests and share your findings here it  will make this plan real for sure.
