### ISSUE TITLE
Rounding error in vqrshrun_n_s64

### ISSUE THREAD

**Issue by joho-11** [intel/ARM_NEON_2_x86_SSE#71]
I believe that line 8770 in NEON_2_SSE.h should changed from this:
        res64 = (atmp[1] >> b) + ( (atmp[0] & ((int64_t)1 << (b - 1))) >> (b - 1)  );
to this:
        res64 = (atmp[1] >> b) + ( (atmp[1] & ((int64_t)1 << (b - 1))) >> (b - 1)  );

Test with a[0] = 291408416384, a[1] = 611251267456, b = 16
res.m64_u32[1]= 9326955, should be 9326954

**Comment by Zvictoria** [comment]
@joho-11 thanks for reporting, to be fixed in the next commit
