### ISSUE TITLE
Incorrect header include

### ISSUE THREAD

**Issue by lordnn** [intel/ARM_NEON_2_x86_SSE#74]
`_mm_loadu_si16()` and some others defined in immintrin.h header, but it's include is under `USE_AVX2` ifdef.
So now it's impossible to compile without `USE_AVX2` definition.
https://github.com/intel/ARM_NEON_2_x86_SSE/blob/18625166e02e743497dad56f5fec049398c97d52/NEON_2_SSE.h#L77-L79

https://github.com/intel/ARM_NEON_2_x86_SSE/blob/18625166e02e743497dad56f5fec049398c97d52/NEON_2_SSE.h#L10629

**Comment by Zvictoria** [comment]
@lordnn thanks a lot for your input, fixed it correctly (I hope :) in the last commit.
