### ISSUE TITLE
compiler error when enable avx2

### ISSUE THREAD

**Issue by suitmyself** [intel/ARM_NEON_2_x86_SSE#78]
codes:
![image](https://github.com/user-attachments/assets/06d0776a-42a1-47ae-bf7a-dae7bb699c5e)

error:
![image](https://github.com/user-attachments/assets/2cd2d42d-a787-41f5-8b37-c7cdacd499b6)

reason:
![image](https://github.com/user-attachments/assets/d2831ac3-6ea8-4815-8a5d-83cec3bbfa9f)

same for other intrinsic:
![image](https://github.com/user-attachments/assets/a0d324d7-5977-4a4f-9914-454f3beaf89a)

**Comment by Zvictoria** [comment]
Thanks for reporting. To be fixed in the next update
