### ISSUE TITLE
how to convert vfmaq_f32  to SSE?

### ISSUE THREAD

**Issue by adeagle** [intel/ARM_NEON_2_x86_SSE#8]

**Comment by Zvictoria** [comment]
Multiply accumulate functions are not a part of a standard arm_neon header, The are not a part of SSE instructions set either but implemented in FMA  instruction set. I might add them in this porting tool as well if there is a need. Could you please explain what project do you need it for? Or you could do it yourself, it  should be easy.

**Comment by adeagle** [comment]
I have change vfmaq_laneq_f32 to vmlaq_lane_f32+vget_low_f32; 
after convert,the speed is faster 2.5X than C code ,is that normal?

**Comment by Zvictoria** [comment]
yes, this level of speedup is expected in such kind of porting.

**Comment by adeagle** [comment]
will you support AVX?

**Comment by Zvictoria** [comment]
The short answer is "May be if there is a real need  for that". The goal of this project has been to simplify porting from ARM based   mobile devices  to Intel Atom based mobile devices. And Atoms don't have AVX. If there appear some important projects for ARM -> x86 desktop porting we may add AVX there

**Comment by caand** [comment]
But AFAIK there is nothing equivalent to AVX on ARM: ARM only has 128bit SIMD.

As Victoria points out, this project targets mobile devices and does a very good job at it. If you need AVX, you are on another platform and you could (should) use directly AVX intrinsics.

Calin

**Comment by adeagle** [comment]
ok.thanks
