### ISSUE TITLE
Any plan for ARMv8/AArch64 NEON support?

### ISSUE THREAD

**Issue by viblo** [intel/ARM_NEON_2_x86_SSE#9]
I wonder if there is any plan for support of 64bit floats, such as `float64x2_t` and functions such as `vdupq_n_f64`. Im very inexperience when it comes to ARM, but it seems like these are part of ARMv8/AArch64.

**Comment by Zvictoria** [comment]
Hi, Victor. To be honest, I don't have any plans for whatever features support :) Such support to be available if there is a need for it in developers community. To be honest it is the first time I see such request, so if more of them comes in I may implement it as well. It should be very simple. However no promises there for obvious reasons...
